//
//  Workspace.swift
//  Packages
//
//  Created by 김동준 on 8/18/24
//

import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: "Omokwan",
    projects: [
        "Projects/Omokwan"
    ],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
